Resources:
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: ChespiTemplate
      LaunchTemplateData:
        ImageId: ami-06b21ccaeff8cd686 # Asegúrate de que sea válido
        InstanceType: t3.micro
        KeyName: chespirito-key
        SecurityGroupIds:
          - sg-0484c4edc7e142078 # Asegúrate de que sea válido
        NetworkInterfaces:
          - AssociatePublicIpAddress: true
            SubnetId: subnet-091bca9d2e5dc7e1d # Asegúrate de que sea válido
      # Otras propiedades opcionales aquí

  AWSEBAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate # Referencia al Launch Template
        Version: $Latest # O puede ser una versión específica
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 1
      VPCZoneIdentifier:
        - subnet-091bca9d2e5dc7e1d
      TargetGroupARNs:
        - !Ref MyTargetGroup
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      Tags:
        - Key: Name
          Value: MyAutoScalingGroup
          PropagateAtLaunch: true
